# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b661f70220ad8af7d1a98d253844aafa2157e82e08ece8582ecc32ff0af6d8eb1c7981ced579bd72ef54655580a52092bc36c07362c850c8d2bd534c93f24064

test:
  secret_key_base: f42e22e53e8e2d7d8b258f600bfc99e93163851a51d5a04ab746c1a8c056196605fda60dade0f56769a70752a8d293cdeb1e5b4dbb75e55114020d3a99784e9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
